// @generated by scripts/generate-upstream-fixtures.py; do not edit by hand.
UpstreamOpusFixture {
    source_commit: "1194c9011fe6402edc7aebe7ffe9650ea3b1afee",
    cases: &[
        OpusEncodedFixture { profile_name: "PROFILE_VOICE_LOW", profile_value: 0, samplerate: 8000, channels: 1, frame_duration_ms: 20, frame_count: 160, max_bytes: 15, hex: "0883caec86317e8f1f9d0414e62f12" },
        OpusEncodedFixture { profile_name: "PROFILE_VOICE_MEDIUM", profile_value: 1, samplerate: 24000, channels: 1, frame_duration_ms: 20, frame_count: 480, max_bytes: 20, hex: "488340bce41e284847a9e5f68591e16d4dcc2f5c" },
        OpusEncodedFixture { profile_name: "PROFILE_VOICE_MAX", profile_value: 3, samplerate: 48000, channels: 2, frame_duration_ms: 20, frame_count: 960, max_bytes: 80, hex: "fc7d5efc0970cd75c96066b65712dc2acc7915d3e78e5f356b6250ae4d465d53c8ec6e28dc91f330fd55490b7c53996d807a5720b1d4af0c7bb6cfc26a5d3b67c756c157be9e05dc4d0cc3e7342d8584" },
        OpusEncodedFixture { profile_name: "PROFILE_AUDIO_LOW", profile_value: 5, samplerate: 12000, channels: 1, frame_duration_ms: 20, frame_count: 240, max_bytes: 35, hex: "28822fdb353d122dba7b3efaee0686a0ced0bdc720ff2618f467a30048615bec5c" },
        OpusEncodedFixture { profile_name: "PROFILE_AUDIO_HIGH", profile_value: 7, samplerate: 48000, channels: 2, frame_duration_ms: 20, frame_count: 960, max_bytes: 140, hex: "fc7d5efc0970cd75c96066b60dfbaacc663c89e8e77c8c8f4b50417249d75401fc771839b81cc66ceec7df48c4b3309d877e23d6f1c24b96de840b37a0dd95eb6f05e749e098a148a85464088c4b280605085663a1d3afcdee9f4500f7085304548b16565125bc046a233f634128ba9f626f5592e7d09547135299cfbb7794e1fb7394e0efd3e4f437480640" },
    ],
}
